project:
  type: manuscript

manuscript: 
  article: Results and Discussion.qmd


author: 
  - name: "Leila Aburomia"
    corresponding: true
  - name: "Aldair Perez"
  - name: "Noah Goodhart"

bibliography: references.bib 
csl: https://www.zotero.org/styles/apa

format:
  html:
    self-contained: true



execute:
  freeze: true



